# this configuration file has all empty custom components set up.
# use 'esphome test_empty.yaml compile' to build. 

packages:
  device: !include device.yaml # include our test device setup

sensor:
  - platform: empty_sensor
    id: empty_sensor_1

  - platform: empty_i2c_sensor
    id: empty_i2c_sensor_1

  - platform: empty_spi_sensor
    id: empty_spi_sensor_1
    cs_pin: D8

  - platform: empty_uart_sensor
    id: empty_uart_sensor_1

  - platform: empty_compound_sensor
    id: empty_compound_sensor_1
    sensor1:
      name: "Sensor 1"
    sensor2:
      name: "Sensor 2"
    sensor3:
      name: "Sensor 3"  

binary_sensor:
  - platform: empty_binary_sensor
    id: empty_binary_sensor_1
  
output:
  - platform: empty_binary_output
    id: empty_binary_output_1

  - platform: empty_float_output
    id: empty_float_output_1

light:
  - platform: empty_light
    id: empty_light_1
    output: empty_float_output_1
    
switch:
  - platform: empty_switch
    id: empty_switch_1

fan:
  - platform: empty_fan
    id: empty_fan_1
    output: empty_binary_output_1

text_sensor:
  - platform: empty_text_sensor
    id: empty_text_sensor_1

cover:
  platform: empty_cover
  id: empty_cover_1

empty_component:
  id: empty_component_1

i2c:
  sda: 4
  scl: 5

empty_i2c_component:
  id: empty_i2c_component_1
  address: 0x01

uart:
  tx_pin: D0
  rx_pin: D1
  baud_rate: 9600

empty_uart_component:
  id: empty_uart_component_1

spi:
  clk_pin: D5
  miso_pin: D6

empty_spi_component:
  id: empty_spi_component_1
  cs_pin: D8