packages:
  device: !include device.yaml

sensor:
  - platform: empty_sensor
    id: empty_sensor_1

binary_sensor:
  - platform: empty_binary_sensor
    id: empty_binary_sensor_1
  
output:
  - platform: empty_binary_output
    id: empty_binary_output_1

  - platform: empty_float_output
    id: empty_float_output_1

light:
  - platform: empty_light
    id: empty_light_1
    output: empty_float_output_1
    
switch:
  - platform: empty_switch
    id: empty_switch_1

fan:
  - platform: empty_fan
    id: empty_fan_1
    output: empty_binary_output_1

text_sensor:
  - platform: empty_text_sensor
    id: empty_text_sensor_1

cover:
  platform: empty_cover
  id: empty_cover_1

empty_component:
  id: empty_component_1